A = float(input("Type you num : "))
B  = float(input("Type you num : "))

print("\n")
print("ผลบวก :", A+B)
print("ผลลบ :", A-B)
print("ผลคูณ :",A*B)
print("ผลหาร :",A/B)
print("ผลหารตัดเศษ :",A//B)
print("ยกกำลัง :",A**B)
print("หารเอาเศษ :",A%B)
